/* Drumul spre Romana — Speech and the audio-asset index.
 *
 * Extracted verbatim from index.html. Everything that decides what a learner
 * hears when they press play: the hand-added asset table, the manifest-backed
 * lookup index built from it, and Speech itself -- the object every play
 * button ultimately calls.
 *
 * AUDIO_ASSETS ships empty; audio-manifest.js (a separate, gitignored,
 * generated script loaded before this one) supplies the real entries at
 * runtime through window.AUDIO_MANIFEST. buildAssetIndex() merges the two,
 * hand-added entries winning, lazily on first use -- AUDIO_ASSET_INDEX stays
 * null until something actually asks for a clip.
 *
 * Speech's fallback order is a content policy, not an implementation detail:
 * a pre-rendered native clip first, a locally installed Romanian voice
 * second, and silence -- never an English-accented approximation -- if
 * neither is available. speakOne() encodes exactly that order and must not be
 * reordered.
 *
 * Speech calls the now-global render() in exactly two places, both gated on
 * whether Romanian voice availability actually flipped since the last check:
 * once from speechSynthesis.onvoiceschanged, and once from three self-check
 * timers ([400, 1200, 3000]ms) that exist because Edge's online neural voices
 * arrive seconds after the offline ones and the audio controls would
 * otherwise keep showing as unavailable after they in fact become available.
 * Neither call was changed by this move -- render() was already reached
 * through the global scope chain before render.js existed as a separate
 * file, since Speech's IIFE runs before render() is declared and JS resolves
 * an unqualified identifier at call time, not at parse time.
 *
 * The "use strict" directive is not new — it is the mode this code already
 * ran in inside the application IIFE, repeated here because a separate
 * classic script would otherwise default to sloppy mode.
 */
"use strict";

/* ===================== SPEECH / AUDIO ABSTRACTION ===================== */
/* ---------------------------------------------------------------------------
   AUDIO ASSETS — prerecorded native-speaker clips, keyed by the exact Romanian
   string they voice. Stored separately from lesson content (per the brief) so
   recordings can be added without touching a single lesson, vocabulary entry
   or exercise.

   Drop in entries as:  "bună ziua": "audio/buna-ziua.mp3"
   or a data: URI. Anything listed here is used in preference to speech
   synthesis. Keys are matched case- and diacritic-insensitively.

   This ships EMPTY: no native recordings are bundled. Until it is populated,
   playback falls back to a Romanian TTS voice — and if none is installed, the
   app refuses to speak rather than mispronouncing Romanian in an English voice.
--------------------------------------------------------------------------- */
var AUDIO_ASSETS = {
  // "bună ziua": "audio/buna-ziua.mp3",
};

/* Pronunciation comes from pre-rendered clips (see audio-manifest.js). Fetching
   Google's translate_tts live from the page is not possible: it rejects
   browser-originated requests — the Sec-Fetch-* / Origin headers mark them as
   hotlinking and it returns an HTML error page instead of audio, and those
   headers are forbidden to JavaScript. tools/fetch_audio.py does the fetching
   from a non-browser client instead, which also makes playback work offline. */
var AUDIO_ASSET_INDEX = null;
function buildAssetIndex(){
  AUDIO_ASSET_INDEX = {};
  /* audio-manifest.js (generated by tools/fetch_audio.py) is keyed by the same
     normLoose() form used here, so it merges in directly. */
  var m = window.AUDIO_MANIFEST;
  if(m) Object.keys(m).forEach(function(k){ AUDIO_ASSET_INDEX[k] = m[k]; });
  /* Hand-added entries win over generated ones. */
  Object.keys(AUDIO_ASSETS).forEach(function(k){ AUDIO_ASSET_INDEX[normLoose(k)] = AUDIO_ASSETS[k]; });
  return AUDIO_ASSET_INDEX;
}
function assetFor(text){
  if(AUDIO_ASSET_INDEX===null) buildAssetIndex();
  var k = normLoose(text);
  if(AUDIO_ASSET_INDEX[k]) return AUDIO_ASSET_INDEX[k];
  /* Poetic elisions (nost', într') are stored under the unelided stem. */
  var stripped = normLoose(String(text||"").replace(/['’]+$/,""));
  return AUDIO_ASSET_INDEX[stripped] || null;
}
function assetCount(){
  if(AUDIO_ASSET_INDEX===null) buildAssetIndex();
  return Object.keys(AUDIO_ASSET_INDEX).length;
}

var Speech = (function(){
  var voices=[], roVoice=null, current=null, audioEl=null, gtFailed=false;

  /* Rank Romanian voices best-first. Edge exposes free online neural voices
     (Emil / Alina, ro-RO) that are modelled on native speakers; those are the
     best available without shipping recordings. Offline SAPI voices come next.
     A non-Romanian voice is NEVER an acceptable fallback. */
  function scoreVoice(v){
    if(!/^ro(-|_|$)/i.test(v.lang)) return -1;
    var n = (v.name||"").toLowerCase();
    var s = 10;
    if(/natural|neural/.test(n)) s += 40;
    if(/online/.test(n)) s += 20;
    if(/\bro-ro\b/i.test(v.lang)) s += 5;
    if(v.localService) s += 3;
    return s;
  }
  function refresh(){
    try{
      voices = window.speechSynthesis ? (window.speechSynthesis.getVoices()||[]) : [];
      var ro = voices.filter(function(v){ return scoreVoice(v) >= 0; })
                     .sort(function(a,b){ return scoreVoice(b)-scoreVoice(a); });
      roVoice = ro[0] || null;
    }catch(e){ voices=[]; roVoice=null; }
    return roVoice;
  }
  if(typeof window!=="undefined" && window.speechSynthesis){
    refresh();
    /* Voice lists populate asynchronously — and on Edge the online neural
       voices arrive seconds after the offline ones. Re-check and repaint so the
       audio controls stop showing as unavailable once Romanian appears. */
    window.speechSynthesis.onvoiceschanged = function(){
      var had = !!roVoice;
      refresh();
      if(!!roVoice !== had && typeof render==="function") render();
    };
    [400, 1200, 3000].forEach(function(ms){
      setTimeout(function(){
        var had = !!roVoice;
        refresh();
        if(!!roVoice !== had && typeof render==="function") render();
      }, ms);
    });
  }
  function hasNativeVoice(){ return !!roVoice; }
  function voiceName(){ return roVoice ? roVoice.name : null; }
  function romanianVoices(){ return voices.filter(function(v){ return scoreVoice(v)>=0; }); }
  /* What will actually happen if the learner presses play on this text. */
  function statusFor(text){
    if(text && assetFor(text)) return "asset";   // pre-rendered Romanian clip
    if(roVoice) return "tts";                    // local Romanian voice
    return "unavailable";                        // refuse — do not mispronounce
  }
  function sourceLabel(){
    if(assetCount()) return "Pre-rendered Romanian clips";
    if(roVoice) return roVoice.name;
    return "unavailable";
  }
  function googleFailed(){ return gtFailed; }
  function resetSource(){ gtFailed = false; AUDIO_ASSET_INDEX = null; }
  function speakLocal(text, rate, opts){
    if(!window.speechSynthesis) return false;
    if(!roVoice) refresh();
    /* REFUSE to speak Romanian in a non-Romanian voice. Reading Romanian
       through an English voice teaches wrong phonology — worse for the learner
       than silence. The UI explains and offers a fix instead. */
    if(!roVoice) return false;
    var u = new SpeechSynthesisUtterance(unifyRomanian(text));
    u.voice = roVoice;
    u.lang = roVoice.lang || "ro-RO";
    u.rate = rate; u.pitch = 1;
    if(opts.onend) u.onend = opts.onend;
    if(opts.onstart) u.onstart = opts.onstart;
    current = u;
    /* Chrome drops an utterance queued in the same tick as cancel(). */
    setTimeout(function(){ try{ window.speechSynthesis.speak(u); }catch(e){} }, 0);
    return true;
  }

  function speak(text, opts){
    stop();
    seqCancelled = false;
    return speakOne(text, opts);
  }
  /* Single utterance, without canceling what's already queued — so
     speakSequence can chain calls without killing its own playback. */
  function speakOne(text, opts){
    opts = opts||{};
    var rate = opts.rate || state.settings.audioSpeed || 1;

    /* 1. A bundled native-speaker recording always wins. */
    var src = assetFor(text);
    if(src){
      try{
        audioEl = new Audio(src);
        audioEl.playbackRate = rate;
        if(opts.onend) audioEl.onended = opts.onend;
        audioEl.onerror = function(){ if(opts.onerror) opts.onerror(); };
        audioEl.play().catch(function(){ if(opts.onerror) opts.onerror(); });
        return {ok:true, mode:"asset"};
      }catch(e){ /* fall through */ }
    }

    /* 2. Locally installed Romanian voice. */
    if(speakLocal(text, rate, opts)) return {ok:true, mode:"tts", voice:roVoice.name};

    /* 3. Nothing correct is available — stay silent and say so. */
    if(opts.onerror) opts.onerror();
    return {ok:false, mode:"unavailable", reason:"no-romanian-voice"};
  }
  /* Play several lines back to back — used for dialogue "Play all" and any
     multi-line passage. Each line resolves to its own clip, so a dialogue never
     depends on a clip existing for the whole concatenated transcript. */
  var seqCancelled = false;
  function speakSequence(texts, opts){
    opts = opts||{};
    stop();
    seqCancelled = false;
    var i = 0;
    function next(){
      if(seqCancelled) return;
      if(i >= texts.length){ if(opts.onend) opts.onend(); return; }
      var t = texts[i++];
      var res = speakOne(t, {
        rate: opts.rate,
        onend: function(){ setTimeout(next, 260); },   // a beat between lines
        onerror: function(){ setTimeout(next, 60); }   // skip a missing clip
      });
      if(!res.ok) setTimeout(next, 60);
    }
    next();
    return {ok:true, mode:"sequence"};
  }
  function stop(){
    current = null;
    seqCancelled = true;
    try{ window.speechSynthesis && window.speechSynthesis.cancel(); }catch(e){}
    if(audioEl){ try{ audioEl.pause(); }catch(e){} audioEl = null; }
  }
  return {speak:speak, speakSequence:speakSequence, stop:stop,
          hasNativeVoice:hasNativeVoice, refresh:refresh,
          voiceName:voiceName, romanianVoices:romanianVoices, statusFor:statusFor,
          sourceLabel:sourceLabel, googleFailed:googleFailed, resetSource:resetSource};
})();
