"""Regenerate audio-manifest.js from whatever clips are currently in audio/.

Runs independently of the downloader, so the manifest can be rebuilt mid-fetch
or after dropping in hand-made recordings.
"""
import io, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fetch_audio import norm_key, clip_name, AUDIO_DIR, MANIFEST  # noqa: E402

strings_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ro-strings.json")
strings = json.load(io.open(strings_path, encoding="utf-8"))

entries, missing = {}, 0
for text in strings:
    text = (text or "").strip()
    if not text or text == "—":
        continue
    p = os.path.join(AUDIO_DIR, clip_name(text))
    if os.path.exists(p) and os.path.getsize(p) > 400:
        entries[norm_key(text)] = "audio/" + clip_name(text)
    else:
        missing += 1

with io.open(MANIFEST, "w", encoding="utf-8") as fh:
    fh.write("/* Generated by tools/build_manifest.py - do not edit by hand.\n"
             "   Maps normalised Romanian text to a pre-rendered clip. */\n")
    fh.write("window.AUDIO_MANIFEST = ")
    json.dump(entries, fh, ensure_ascii=False, indent=0, sort_keys=True)
    fh.write(";\n")

total = os.path.getsize(MANIFEST)
print("manifest: %d clips mapped, %d still missing (%d bytes)" % (len(entries), missing, total))
